=== tpidgur/Epam_Course_Project_3/src/settings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
           attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="plane">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="model" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="origin"/>
              <xs:element name="chars">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element  name="type">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="fighter"/>
                        <xs:enumeration value="support"/>
                        <xs:enumeration value="convoy"/>
                        <xs:enumeration value="interceptor"/>
                        <xs:enumeration value="reconnaissance"/>
                      </xs:restriction>
                    </xs:simpleType>
                   </xs:element>
                    <xs:element name="seat_number">
                      <xs:simpleType >
                        <xs:restriction base="xs:byte">
                          <xs:minInclusive value="1"/>
                          <xs:maxInclusive value="2"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="ammunition_load">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element  name="missile_number">
                            <xs:simpleType >
                              <xs:restriction base="xs:int">
                                <xs:minInclusive value="0"/>
                                <xs:maxInclusive value="10"/>
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:boolean" name="radar"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="parameters">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:float" name="length"/>
                    <xs:element type="xs:float" name="width"/>
                    <xs:element type="xs:float" name="height"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="price">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:short">
                      <xs:attribute type="xs:string" name="unit" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="required"/>
            <xs:attribute type="xs:string" name="modelId" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>

    </xs:complexType>
  </xs:element>
</xs:schema>

=== tpidgur/Epam_Course_Project_3/src/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<plane
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="settings.xsd">
    <model name="Mig-29" modelId="123">
        <origin>USSR</origin>
        <chars>
            <type>fighter</type>
            <seat_number>2</seat_number>
            <ammunition_load>
                <missile_number>3</missile_number>
            </ammunition_load>
            <radar>true</radar>
        </chars>
        <parameters>
            <length>17.32</length>
            <width>11.36</width>
            <height>4.73</height>
        </parameters>
        <price unit="taller">100</price>
    </model>
    <model name="F-14" modelId="124">
        <origin>USA</origin>
        <chars>
            <type>fighter</type>
            <seat_number>2</seat_number>
            <ammunition_load><missile_number>4</missile_number></ammunition_load>
            <radar>true</radar>
        </chars>
        <parameters>
            <length>19.1</length>
            <width>19.45</width>
            <height>4.88</height>
        </parameters>
        <price unit="taller">200</price>
    </model>
    <model name="F-18" modelId="125">
        <origin>USA</origin>
        <chars>
            <type>fighter</type>
            <seat_number>2</seat_number>
            <ammunition_load>
                <missile_number>5</missile_number>
            </ammunition_load>
            <radar>true</radar>
        </chars>
        <parameters>
            <length>17</length>
            <width>12</width>
            <height>4.73</height>
        </parameters>
        <price unit="taller">200</price>
    </model>
    <model name="EF-2000" modelId="126">
        <origin>EU</origin>
        <chars>
            <type>fighter</type>
            <seat_number>2</seat_number>
            <ammunition_load>
                <missile_number>10</missile_number>
            </ammunition_load>
            <radar>true</radar>
        </chars>
        <parameters>
            <length>15.96</length>
            <width>10.95</width>
            <height>5.28</height>
        </parameters>
        <price unit="taller">300</price>
    </model>
</plane>
